<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 08 May 2013 03:43:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_vkontakte_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['membersVkontakteConnect'] = array('vkHasPic','vkHasPic','vkPassword');


}

/* -- membersVkontakteConnect --*/
function membersVkontakteConnect($isConnected, $userData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_vkontakte', $this->_funcHooks['membersVkontakteConnect'] ) )
{
$count_06b557b9cd15a9835dc4f4db8fabe6c2 = is_array($this->functionData['membersVkontakteConnect']) ? count($this->functionData['membersVkontakteConnect']) : 0;
$this->functionData['membersVkontakteConnect'][$count_06b557b9cd15a9835dc4f4db8fabe6c2]['isConnected'] = $isConnected;
$this->functionData['membersVkontakteConnect'][$count_06b557b9cd15a9835dc4f4db8fabe6c2]['userData'] = $userData;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- vkInlineLogInService --*/
function vkInlineLogInService() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- vkServicesLim --*/
function vkServicesLim() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>