<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 08 May 2013 03:43:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ucp_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['coreAttachments'] = array('attachmentThumbLocation','attachmentPost','attach','attachAlmostFull','hasAttachLimit','hasPagesTop','hasAttachments','attachmentMultiDelete','hasPagesBottom');
$this->_funcHooks['displayNameForm'] = array('dnameOkMessage','dnameFbUser');
$this->_funcHooks['emailPasswordChangeForm'] = array('hideMessageIfAdmin','emailIsAdmin','passFbUser','removeUser','removeUser2','removeUser3','removeUser4','emailIsNotAdmin');
$this->_funcHooks['field_entry'] = array('cfieldDesc','cfieldDesc');
$this->_funcHooks['membersFacebookConnect'] = array('fbShowStatus','fbSyncPic','fbSyncStatus','canUpdateStatus','fbSyncStatus','statusImportGroup','fbLastSync','pImgOA','pCheckOA','pImgE','pCheckE','pImgPS','pCheckPS','pImgRS','pCheckRS','fbPassword','fbDefaultEmail','fbMismatch');
$this->_funcHooks['membersIgnoredUsersForm'] = array('ignoreMemberTopics','ignoreMemberSigs','ignoreGlobal','ignoreMemberPms','ignoreUserchats','hasChatRow','members','canSee','topPagination','hasChat','hasChatNone','bottomPagination','hasChatRowCheckbox');
$this->_funcHooks['membersProfileForm'] = array('isOurTimezone','timezones','monthSelected','months','daySelected','days','yearSelected','years','canUploadPhoto','dstError','doAutoDst','doManualDst','doManualDst','showComments','yesModComments','showLastVisitors','showFriends','yesModFriends','friendsEnabled','changeMemberTitle','birthdayFields','showProfileInfo','requiredCfields','optionalCfields');
$this->_funcHooks['membersSignatureForm'] = array('hasSignatureLimits','htmlModeOn','canUseHtml','disablelightbox');
$this->_funcHooks['membersTwitterConnect'] = array('tcHasPic','tcShowStatus','tcHasPic','tcLastSync','tcSyncPic','tcSyncStatus','tcSyncIStatus','statusImportGroup','tcSyncAboutMe','tcSyncBgImg','canBG','twitterPassword');
$this->_funcHooks['notificationsForm'] = array('hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','keyExists','groupKeys','isPrivateMsg','badConfig','isTopicsOrPosts','notifyGroupsList','isCoreNot','updateLastApp','newNotApp','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','keyNotDone','notifyOther','allowAdminMails');
$this->_funcHooks['notificationsLog'] = array('hasReadNotify','hasReadNotify','categories','hasconfirm','hasnotifyerror','hasNotifications','hasNotifyForMod','notifications');
$this->_funcHooks['userCPTemplate'] = array('isSettings','isSettingsInactive','active_tab','tabs','tabsMenus_active','items','errors','has_max_upload','usercp_form','hasMoreThanOneTabClass','hasMoreThanOneTabSidebar','hasMoreThanOneTabClassContent','has_errors','didSave','submit_button','end_form');


}

/* -- coreAttachments --*/
function coreAttachments($info="",$pages="",$attachments) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['coreAttachments'] ) )
{
$count_620fd272c61c05a0846ac1c65c3d6458 = is_array($this->functionData['coreAttachments']) ? count($this->functionData['coreAttachments']) : 0;
$this->functionData['coreAttachments'][$count_620fd272c61c05a0846ac1c65c3d6458]['info'] = $info;
$this->functionData['coreAttachments'][$count_620fd272c61c05a0846ac1c65c3d6458]['pages'] = $pages;
$this->functionData['coreAttachments'][$count_620fd272c61c05a0846ac1c65c3d6458]['attachments'] = $attachments;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayNameForm --*/
function displayNameForm($form=array(),$error="",$okmessage="", $isFB=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['displayNameForm'] ) )
{
$count_fb443c84b1fa296fb3db5fa6f7ac4420 = is_array($this->functionData['displayNameForm']) ? count($this->functionData['displayNameForm']) : 0;
$this->functionData['displayNameForm'][$count_fb443c84b1fa296fb3db5fa6f7ac4420]['form'] = $form;
$this->functionData['displayNameForm'][$count_fb443c84b1fa296fb3db5fa6f7ac4420]['error'] = $error;
$this->functionData['displayNameForm'][$count_fb443c84b1fa296fb3db5fa6f7ac4420]['okmessage'] = $okmessage;
$this->functionData['displayNameForm'][$count_fb443c84b1fa296fb3db5fa6f7ac4420]['isFB'] = $isFB;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- emailPasswordChangeForm --*/
function emailPasswordChangeForm($txt, $_message, $isFB=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['emailPasswordChangeForm'] ) )
{
$count_450eb1a542c5caa8073329ad1bb8c926 = is_array($this->functionData['emailPasswordChangeForm']) ? count($this->functionData['emailPasswordChangeForm']) : 0;
$this->functionData['emailPasswordChangeForm'][$count_450eb1a542c5caa8073329ad1bb8c926]['txt'] = $txt;
$this->functionData['emailPasswordChangeForm'][$count_450eb1a542c5caa8073329ad1bb8c926]['_message'] = $_message;
$this->functionData['emailPasswordChangeForm'][$count_450eb1a542c5caa8073329ad1bb8c926]['isFB'] = $isFB;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_dropdown --*/
function field_dropdown($name="",$options="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_entry --*/
function field_entry($title="",$desc="",$content="",$id="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['field_entry'] ) )
{
$count_3893f3a6acf5884c37c457839d54d04d = is_array($this->functionData['field_entry']) ? count($this->functionData['field_entry']) : 0;
$this->functionData['field_entry'][$count_3893f3a6acf5884c37c457839d54d04d]['title'] = $title;
$this->functionData['field_entry'][$count_3893f3a6acf5884c37c457839d54d04d]['desc'] = $desc;
$this->functionData['field_entry'][$count_3893f3a6acf5884c37c457839d54d04d]['content'] = $content;
$this->functionData['field_entry'][$count_3893f3a6acf5884c37c457839d54d04d]['id'] = $id;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_textarea --*/
function field_textarea($name="",$value="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_textinput --*/
function field_textinput($name="",$value="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersFacebookConnect --*/
function membersFacebookConnect($fbuid, $fbUserData, $linkedMemberData, $perms) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersFacebookConnect'] ) )
{
$count_d25863c57321de99442c1c4f4748fbf5 = is_array($this->functionData['membersFacebookConnect']) ? count($this->functionData['membersFacebookConnect']) : 0;
$this->functionData['membersFacebookConnect'][$count_d25863c57321de99442c1c4f4748fbf5]['fbuid'] = $fbuid;
$this->functionData['membersFacebookConnect'][$count_d25863c57321de99442c1c4f4748fbf5]['fbUserData'] = $fbUserData;
$this->functionData['membersFacebookConnect'][$count_d25863c57321de99442c1c4f4748fbf5]['linkedMemberData'] = $linkedMemberData;
$this->functionData['membersFacebookConnect'][$count_d25863c57321de99442c1c4f4748fbf5]['perms'] = $perms;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersIgnoredUsersForm --*/
function membersIgnoredUsersForm($members) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersIgnoredUsersForm'] ) )
{
$count_bbf865c1dcce61be125e3dc98115d363 = is_array($this->functionData['membersIgnoredUsersForm']) ? count($this->functionData['membersIgnoredUsersForm']) : 0;
$this->functionData['membersIgnoredUsersForm'][$count_bbf865c1dcce61be125e3dc98115d363]['members'] = $members;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersProfileCustomize --*/
function membersProfileCustomize($options, $input, $errors) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersProfileForm --*/
function membersProfileForm($custom_fields='',$group_titles='',$day='',$mon='',$year='', $amEditor='', $times=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersProfileForm'] ) )
{
$count_d9368cbcb46ca805e7b20802720d529f = is_array($this->functionData['membersProfileForm']) ? count($this->functionData['membersProfileForm']) : 0;
$this->functionData['membersProfileForm'][$count_d9368cbcb46ca805e7b20802720d529f]['custom_fields'] = $custom_fields;
$this->functionData['membersProfileForm'][$count_d9368cbcb46ca805e7b20802720d529f]['group_titles'] = $group_titles;
$this->functionData['membersProfileForm'][$count_d9368cbcb46ca805e7b20802720d529f]['day'] = $day;
$this->functionData['membersProfileForm'][$count_d9368cbcb46ca805e7b20802720d529f]['mon'] = $mon;
$this->functionData['membersProfileForm'][$count_d9368cbcb46ca805e7b20802720d529f]['year'] = $year;
$this->functionData['membersProfileForm'][$count_d9368cbcb46ca805e7b20802720d529f]['amEditor'] = $amEditor;
$this->functionData['membersProfileForm'][$count_d9368cbcb46ca805e7b20802720d529f]['times'] = $times;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- membersSignatureForm --*/
function membersSignatureForm($editor_html="",$sig_restrictions=array(),$signature='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersSignatureForm'] ) )
{
$count_0639552e4eb91ea428f29e8b83949d8a = is_array($this->functionData['membersSignatureForm']) ? count($this->functionData['membersSignatureForm']) : 0;
$this->functionData['membersSignatureForm'][$count_0639552e4eb91ea428f29e8b83949d8a]['editor_html'] = $editor_html;
$this->functionData['membersSignatureForm'][$count_0639552e4eb91ea428f29e8b83949d8a]['sig_restrictions'] = $sig_restrictions;
$this->functionData['membersSignatureForm'][$count_0639552e4eb91ea428f29e8b83949d8a]['signature'] = $signature;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersSignatureFormError --*/
function membersSignatureFormError($form) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersTwitterConnect --*/
function membersTwitterConnect($isConnected, $twitterUser=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersTwitterConnect'] ) )
{
$count_10df5839f3fc993fb8bd6a6271125ab4 = is_array($this->functionData['membersTwitterConnect']) ? count($this->functionData['membersTwitterConnect']) : 0;
$this->functionData['membersTwitterConnect'][$count_10df5839f3fc993fb8bd6a6271125ab4]['isConnected'] = $isConnected;
$this->functionData['membersTwitterConnect'][$count_10df5839f3fc993fb8bd6a6271125ab4]['twitterUser'] = $twitterUser;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- notificationsForm --*/
function notificationsForm($config, $emailData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['notificationsForm'] ) )
{
$count_48a9927069d45be7240bbd3d61f584ea = is_array($this->functionData['notificationsForm']) ? count($this->functionData['notificationsForm']) : 0;
$this->functionData['notificationsForm'][$count_48a9927069d45be7240bbd3d61f584ea]['config'] = $config;
$this->functionData['notificationsForm'][$count_48a9927069d45be7240bbd3d61f584ea]['emailData'] = $emailData;
}
$IPBHTML .= "test";
return $IPBHTML;
}

/* -- notificationsLog --*/
function notificationsLog($notifications, $error='', $pages='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['notificationsLog'] ) )
{
$count_5fa73275edc58284fbaad5a41078e2d7 = is_array($this->functionData['notificationsLog']) ? count($this->functionData['notificationsLog']) : 0;
$this->functionData['notificationsLog'][$count_5fa73275edc58284fbaad5a41078e2d7]['notifications'] = $notifications;
$this->functionData['notificationsLog'][$count_5fa73275edc58284fbaad5a41078e2d7]['error'] = $error;
$this->functionData['notificationsLog'][$count_5fa73275edc58284fbaad5a41078e2d7]['pages'] = $pages;
}
$IPBHTML .= "<template>popoverNotifications</template>
<notifications>
	".$this->__f__8017eb87a839e27aa988403a6bd29e53($notifications,$error,$pages)."</notifications>";
return $IPBHTML;
}


function __f__8017eb87a839e27aa988403a6bd29e53($notifications, $error='', $pages='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $notifications as $notification )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<notification>
			<id>{$notification['notify_id']}</id>
			<url><![CDATA[{$notification['notify_url']}]]></url>
			<icon><![CDATA[{$notification['member']['pp_thumb_photo']}]]></icon>
			<text><![CDATA[{$notification['notify_title']}]]></text>
		</notification>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- showNotification --*/
function showNotification($notification) {
$IPBHTML = "";
$IPBHTML .= "test";
return $IPBHTML;
}

/* -- userCPTemplate --*/
function userCPTemplate($current_tab, $html, $tabs, $current_area, $errors=array(), $hide_form=0, $maxUpload=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['userCPTemplate'] ) )
{
$count_88d986119ca8a5b90db51f3f187e001b = is_array($this->functionData['userCPTemplate']) ? count($this->functionData['userCPTemplate']) : 0;
$this->functionData['userCPTemplate'][$count_88d986119ca8a5b90db51f3f187e001b]['current_tab'] = $current_tab;
$this->functionData['userCPTemplate'][$count_88d986119ca8a5b90db51f3f187e001b]['html'] = $html;
$this->functionData['userCPTemplate'][$count_88d986119ca8a5b90db51f3f187e001b]['tabs'] = $tabs;
$this->functionData['userCPTemplate'][$count_88d986119ca8a5b90db51f3f187e001b]['current_area'] = $current_area;
$this->functionData['userCPTemplate'][$count_88d986119ca8a5b90db51f3f187e001b]['errors'] = $errors;
$this->functionData['userCPTemplate'][$count_88d986119ca8a5b90db51f3f187e001b]['hide_form'] = $hide_form;
$this->functionData['userCPTemplate'][$count_88d986119ca8a5b90db51f3f187e001b]['maxUpload'] = $maxUpload;
}
$IPBHTML .= "{$html}";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>