<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 08 May 2013 03:43:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_comments_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['comment'] = array('canEditNoPost','commentQueued','userIgnoredLang','hasauthormemid','hasauthormidclose','commentignored','authorwarn','moderateCheckbox','enableRep','hasQ','canReply','canEdit','canHide','canApprove','canDelete','hasReport','commentinitignored');
$this->_funcHooks['commentHidden'] = array('canEditNoPost','moderateCheckbox','canUnhide','canDelete');
$this->_funcHooks['commentsList'] = array('comments','comments_top','comments_bottom','hasCaptcha','guestName','allow_comments');
$this->_funcHooks['form'] = array('comment_errors','isEditing','guest_captcha');


}

/* -- comment --*/
function comment($r, $parent, $settings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['comment'] ) )
{
$count_ad43bc07bb6e86e568dc492e6b72e16f = is_array($this->functionData['comment']) ? count($this->functionData['comment']) : 0;
$this->functionData['comment'][$count_ad43bc07bb6e86e568dc492e6b72e16f]['r'] = $r;
$this->functionData['comment'][$count_ad43bc07bb6e86e568dc492e6b72e16f]['parent'] = $parent;
$this->functionData['comment'][$count_ad43bc07bb6e86e568dc492e6b72e16f]['settings'] = $settings;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- commentHidden --*/
function commentHidden($r, $parent, $settings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentHidden'] ) )
{
$count_3b1da0eb075d3dc77e191d45a188d85b = is_array($this->functionData['commentHidden']) ? count($this->functionData['commentHidden']) : 0;
$this->functionData['commentHidden'][$count_3b1da0eb075d3dc77e191d45a188d85b]['r'] = $r;
$this->functionData['commentHidden'][$count_3b1da0eb075d3dc77e191d45a188d85b]['parent'] = $parent;
$this->functionData['commentHidden'][$count_3b1da0eb075d3dc77e191d45a188d85b]['settings'] = $settings;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- commentsList --*/
function commentsList($comments, $settings, $pages, $parent, $preReply='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentsList'] ) )
{
$count_047e8847e0b42f1610bfba64b1a73961 = is_array($this->functionData['commentsList']) ? count($this->functionData['commentsList']) : 0;
$this->functionData['commentsList'][$count_047e8847e0b42f1610bfba64b1a73961]['comments'] = $comments;
$this->functionData['commentsList'][$count_047e8847e0b42f1610bfba64b1a73961]['settings'] = $settings;
$this->functionData['commentsList'][$count_047e8847e0b42f1610bfba64b1a73961]['pages'] = $pages;
$this->functionData['commentsList'][$count_047e8847e0b42f1610bfba64b1a73961]['parent'] = $parent;
$this->functionData['commentsList'][$count_047e8847e0b42f1610bfba64b1a73961]['preReply'] = $preReply;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- form --*/
function form($comment, $parent, $editor="", $settings, $errors="", $do='saveEdit') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['form'] ) )
{
$count_0652dacff87870bc1190b4888274c86e = is_array($this->functionData['form']) ? count($this->functionData['form']) : 0;
$this->functionData['form'][$count_0652dacff87870bc1190b4888274c86e]['comment'] = $comment;
$this->functionData['form'][$count_0652dacff87870bc1190b4888274c86e]['parent'] = $parent;
$this->functionData['form'][$count_0652dacff87870bc1190b4888274c86e]['editor'] = $editor;
$this->functionData['form'][$count_0652dacff87870bc1190b4888274c86e]['settings'] = $settings;
$this->functionData['form'][$count_0652dacff87870bc1190b4888274c86e]['errors'] = $errors;
$this->functionData['form'][$count_0652dacff87870bc1190b4888274c86e]['do'] = $do;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- getEditJs --*/
function getEditJs() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>