<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 08 May 2013 03:43:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_search_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['asForumPosts'] = array('notLastFtAsForum','topicsForumTrail','moderated','postMid','postModSelected','postModCheckbox','postMember','hasForumTrail');
$this->_funcHooks['asForumTopics'] = array('notLastFtAsForum','topicsForumTrail','haslastpage','pages','archivedBadge','hasPrefix','resultIsPostTR','isNewPostTR','hasTags','multipages','bothSearchUnderTitle','isFollowedStuff','replylang','bothSearch','forumsDigests','isArchivedCb','isAdmin','isFollowedStuff','notLastFtAsForum','topicsForumTrail','resultIsPostAsForum','isNewPostAsForum');
$this->_funcHooks['followData'] = array('hasFrequence','isAnonymous');
$this->_funcHooks['followedContentForumsWrapper'] = array('NCresultsAsForum');
$this->_funcHooks['followedContentForumsWrapperForums'] = array('showSubForumsLit','subforums','showSubForums','isFollowedStuff','hasphoto','lastPosterID','hideDateUrl','hasLastTopicId','hideLastInfo','forumsDigests','NCresultsAsForum');
$this->_funcHooks['followedContentView'] = array('appIsSearched','supportsLikes','apps','hasconfirm','haslikeserror','forumsTab','memberFollow','membersTab','memberFollow','searchedApp','forumsDigests','hasLikeForMod','NPTotal');
$this->_funcHooks['forumAdvancedSearchFilters'] = array('hasArchives');
$this->_funcHooks['forumsVncFilters'] = array('hasFiltersSet','depth','hasFiltersSet','hasTitle','forumlist','noFiltersSet','noFiltersSet');
$this->_funcHooks['helpSearchResult'] = array('showHelpContent');
$this->_funcHooks['memberCommentsSearchResult'] = array('isUpdate','hasMore','maxReplies');
$this->_funcHooks['newContentView'] = array('appIsSearched','appIsSearchable','apps','forumsTab','membersTab','helpTab','hazVNC','hazMember','checked','hasFilters','vncFilterForumsOnly','canFollowFilter','searchismod','NPTotal');
$this->_funcHooks['searchAdvancedForm'] = array('appLoop','calendarlocale','searchTermsRemoved','searchError','isFullText','tagyouareit');
$this->_funcHooks['searchResults'] = array('subResult','results','hasResults','subResult','results');
$this->_funcHooks['searchResultsAsForum'] = array('NCresultsAsForum','asTawpiks','asPostsStart','asPostsEnd','isAdminBottom','isAdmin','disablelightbox','asTawpiks2');
$this->_funcHooks['searchResultsWrapper'] = array('appIsSearched','appIsSearchable','apps','hasSearchResultsCut','hasSearchResultsTags','hasSearchResults','forumsTab','membersTab','helpTab','searchismod','noResultsTerm','hasTotal');
$this->_funcHooks['searchRowGenericFormat'] = array('showGenericContent','isUpdated','hasMemberId','isUpdatedOrHasMemberId');
$this->_funcHooks['topicPostSearchResultAsForum'] = array('whichWayToGo');
$this->_funcHooks['userPostsView'] = array('appIsSearched','appIsSearchable','apps','NPhasResults','forumsTab','membersTab','helpTab','searchismod','NPTotal');


}

/* -- asForumPosts --*/
function asForumPosts($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['asForumPosts'] ) )
{
$count_90ea727ae9e3514fb03c98178cf7dd2b = is_array($this->functionData['asForumPosts']) ? count($this->functionData['asForumPosts']) : 0;
$this->functionData['asForumPosts'][$count_90ea727ae9e3514fb03c98178cf7dd2b]['data'] = $data;
}
$IPBHTML .= "<template>searchResultsAsPost</template>
<searchResults>
</searchResults>";
return $IPBHTML;
}

/* -- asForumTopics --*/
function asForumTopics($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['asForumTopics'] ) )
{
$count_a92c3b012f23ef34846c66d2fd8dabec = is_array($this->functionData['asForumTopics']) ? count($this->functionData['asForumTopics']) : 0;
$this->functionData['asForumTopics'][$count_a92c3b012f23ef34846c66d2fd8dabec]['data'] = $data;
}
$IPBHTML .= "<searchResult>
	<tid>{$data['tid']}</tid>
	<title>{$data['_shortTitle']}</title>
	<state>{$data['state']}</state>
	<url>" . (($data['_unreadUrl']) ? ("{$data['_unreadUrl']}") : ("" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['type_id_2']}&amp;view=" . (($this->request['do']=='new_posts' OR $this->request['do']=='active') ? ("getnewpost") : ("" . (($data['misc']) ? ("findpost&amp;p={$data['misc']}") : ("")) . "")) . "&amp;hl={$this->request['search_higlight']}&amp;fromsearch=1", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "")) . "</url>
	<isRead>" . (($data['_isRead'] == 1) ? ("1") : ("0")) . "</isRead>
	<authorid>{$data['author_id']}</authorid>
	<author>{$data['author_name']}</author>
	".$this->__f__23a7e0847cecbd12a1cceb92de8bf1de($data)."</searchResult>";
return $IPBHTML;
}


function __f__23a7e0847cecbd12a1cceb92de8bf1de($data)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['_forum_trail'] as $i => $f )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "" . (($i+1 == count( $data['_forum_trail'] )) ? ("<forum>{$f[0]}</forum>") : ("")) . "
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- followData --*/
function followData($followData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followData'] ) )
{
$count_0415b381c1b458a872de0acc4efdc9c6 = is_array($this->functionData['followData']) ? count($this->functionData['followData']) : 0;
$this->functionData['followData'][$count_0415b381c1b458a872de0acc4efdc9c6]['followData'] = $followData;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapper --*/
function followedContentForumsWrapper($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentForumsWrapper'] ) )
{
$count_fce839e0041d4cc12c66e5668894a3c4 = is_array($this->functionData['followedContentForumsWrapper']) ? count($this->functionData['followedContentForumsWrapper']) : 0;
$this->functionData['followedContentForumsWrapper'][$count_fce839e0041d4cc12c66e5668894a3c4]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapperForums --*/
function followedContentForumsWrapperForums($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentForumsWrapperForums'] ) )
{
$count_22c7ea5fa59d1b0776ec072145578ba5 = is_array($this->functionData['followedContentForumsWrapperForums']) ? count($this->functionData['followedContentForumsWrapperForums']) : 0;
$this->functionData['followedContentForumsWrapperForums'][$count_22c7ea5fa59d1b0776ec072145578ba5]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentView --*/
function followedContentView($results, $pagination, $total, $error, $contentTypes) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentView'] ) )
{
$count_1a9c19e24342ac3da6d0c0eefc39c64d = is_array($this->functionData['followedContentView']) ? count($this->functionData['followedContentView']) : 0;
$this->functionData['followedContentView'][$count_1a9c19e24342ac3da6d0c0eefc39c64d]['results'] = $results;
$this->functionData['followedContentView'][$count_1a9c19e24342ac3da6d0c0eefc39c64d]['pagination'] = $pagination;
$this->functionData['followedContentView'][$count_1a9c19e24342ac3da6d0c0eefc39c64d]['total'] = $total;
$this->functionData['followedContentView'][$count_1a9c19e24342ac3da6d0c0eefc39c64d]['error'] = $error;
$this->functionData['followedContentView'][$count_1a9c19e24342ac3da6d0c0eefc39c64d]['contentTypes'] = $contentTypes;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumAdvancedSearchFilters --*/
function forumAdvancedSearchFilters($forums, $archivedPostCount=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['forumAdvancedSearchFilters'] ) )
{
$count_3b01dd0f6bf187702d1c4fd9cbb56d7b = is_array($this->functionData['forumAdvancedSearchFilters']) ? count($this->functionData['forumAdvancedSearchFilters']) : 0;
$this->functionData['forumAdvancedSearchFilters'][$count_3b01dd0f6bf187702d1c4fd9cbb56d7b]['forums'] = $forums;
$this->functionData['forumAdvancedSearchFilters'][$count_3b01dd0f6bf187702d1c4fd9cbb56d7b]['archivedPostCount'] = $archivedPostCount;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumsVncFilters --*/
function forumsVncFilters($data, $currentPrefs) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['forumsVncFilters'] ) )
{
$count_338227ef5a4404d3f453cababbc8eb14 = is_array($this->functionData['forumsVncFilters']) ? count($this->functionData['forumsVncFilters']) : 0;
$this->functionData['forumsVncFilters'][$count_338227ef5a4404d3f453cababbc8eb14]['data'] = $data;
$this->functionData['forumsVncFilters'][$count_338227ef5a4404d3f453cababbc8eb14]['currentPrefs'] = $currentPrefs;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- helpSearchResult --*/
function helpSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['helpSearchResult'] ) )
{
$count_2895500fb391907cdcb92956fc151e6d = is_array($this->functionData['helpSearchResult']) ? count($this->functionData['helpSearchResult']) : 0;
$this->functionData['helpSearchResult'][$count_2895500fb391907cdcb92956fc151e6d]['r'] = $r;
$this->functionData['helpSearchResult'][$count_2895500fb391907cdcb92956fc151e6d]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberCommentsSearchResult --*/
function memberCommentsSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['memberCommentsSearchResult'] ) )
{
$count_67cc80461a1f27412409cf6c740ddae4 = is_array($this->functionData['memberCommentsSearchResult']) ? count($this->functionData['memberCommentsSearchResult']) : 0;
$this->functionData['memberCommentsSearchResult'][$count_67cc80461a1f27412409cf6c740ddae4]['r'] = $r;
$this->functionData['memberCommentsSearchResult'][$count_67cc80461a1f27412409cf6c740ddae4]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberSearchResult --*/
function memberSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- newContentView --*/
function newContentView($results, $pagination, $total, $sortDropDown, $sortIn, $dateCutSet=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['newContentView'] ) )
{
$count_8e63e7067c43c3c3f56e9ffd86c36381 = is_array($this->functionData['newContentView']) ? count($this->functionData['newContentView']) : 0;
$this->functionData['newContentView'][$count_8e63e7067c43c3c3f56e9ffd86c36381]['results'] = $results;
$this->functionData['newContentView'][$count_8e63e7067c43c3c3f56e9ffd86c36381]['pagination'] = $pagination;
$this->functionData['newContentView'][$count_8e63e7067c43c3c3f56e9ffd86c36381]['total'] = $total;
$this->functionData['newContentView'][$count_8e63e7067c43c3c3f56e9ffd86c36381]['sortDropDown'] = $sortDropDown;
$this->functionData['newContentView'][$count_8e63e7067c43c3c3f56e9ffd86c36381]['sortIn'] = $sortIn;
$this->functionData['newContentView'][$count_8e63e7067c43c3c3f56e9ffd86c36381]['dateCutSet'] = $dateCutSet;
}
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchAdvancedForm --*/
function searchAdvancedForm($filters='', $msg='', $current_app, $removed_search_terms=array(), $isFT=false, $canTag=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchAdvancedForm'] ) )
{
$count_bd30dec81c40502b8ed7dfcfc5b61215 = is_array($this->functionData['searchAdvancedForm']) ? count($this->functionData['searchAdvancedForm']) : 0;
$this->functionData['searchAdvancedForm'][$count_bd30dec81c40502b8ed7dfcfc5b61215]['filters'] = $filters;
$this->functionData['searchAdvancedForm'][$count_bd30dec81c40502b8ed7dfcfc5b61215]['msg'] = $msg;
$this->functionData['searchAdvancedForm'][$count_bd30dec81c40502b8ed7dfcfc5b61215]['current_app'] = $current_app;
$this->functionData['searchAdvancedForm'][$count_bd30dec81c40502b8ed7dfcfc5b61215]['removed_search_terms'] = $removed_search_terms;
$this->functionData['searchAdvancedForm'][$count_bd30dec81c40502b8ed7dfcfc5b61215]['isFT'] = $isFT;
$this->functionData['searchAdvancedForm'][$count_bd30dec81c40502b8ed7dfcfc5b61215]['canTag'] = $canTag;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- searchResults --*/
function searchResults($results, $titlesOnly) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResults'] ) )
{
$count_dbb4fe02c10b54b0b5b2494a6234e834 = is_array($this->functionData['searchResults']) ? count($this->functionData['searchResults']) : 0;
$this->functionData['searchResults'][$count_dbb4fe02c10b54b0b5b2494a6234e834]['results'] = $results;
$this->functionData['searchResults'][$count_dbb4fe02c10b54b0b5b2494a6234e834]['titlesOnly'] = $titlesOnly;
}
$IPBHTML .= "" . ((is_array( $results )) ? ("".$this->__f__53b2ff0fc6ec6998398689060530984b($results,$titlesOnly)."		") : ("")) . "";
return $IPBHTML;
}


function __f__53b2ff0fc6ec6998398689060530984b($results, $titlesOnly)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $results as $result )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . (($result['sub']) ? ("
					{$result['html']}
				
			") : ("
					{$result['html']}
				
			")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- searchResultsAsForum --*/
function searchResultsAsForum($results, $titlesOnly) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResultsAsForum'] ) )
{
$count_03b21a5ea12c59fbf2969a9df84caddc = is_array($this->functionData['searchResultsAsForum']) ? count($this->functionData['searchResultsAsForum']) : 0;
$this->functionData['searchResultsAsForum'][$count_03b21a5ea12c59fbf2969a9df84caddc]['results'] = $results;
$this->functionData['searchResultsAsForum'][$count_03b21a5ea12c59fbf2969a9df84caddc]['titlesOnly'] = $titlesOnly;
}
$IPBHTML .= "<template>searchResultsAsTopic</template>
<searchResults>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'searchResults' ) ? $this->registry->getClass('output')->getTemplate('search')->searchResults($results, $titlesOnly) : '' ) . "
</searchResults>";
return $IPBHTML;
}

/* -- searchResultsWrapper --*/
function searchResultsWrapper($results, $sortDropDown, $sortIn, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $limited=0, $wasLimited=false, $search_tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResultsWrapper'] ) )
{
$count_79dc9b071c8137be9e50f02e2b9e52c1 = is_array($this->functionData['searchResultsWrapper']) ? count($this->functionData['searchResultsWrapper']) : 0;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['results'] = $results;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['sortDropDown'] = $sortDropDown;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['sortIn'] = $sortIn;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['pagination'] = $pagination;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['total'] = $total;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['showing'] = $showing;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['search_term'] = $search_term;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['url_string'] = $url_string;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['current_key'] = $current_key;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['removed_search_terms'] = $removed_search_terms;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['limited'] = $limited;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['wasLimited'] = $wasLimited;
$this->functionData['searchResultsWrapper'][$count_79dc9b071c8137be9e50f02e2b9e52c1]['search_tags'] = $search_tags;
}
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchRowGenericFormat --*/
function searchRowGenericFormat($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchRowGenericFormat'] ) )
{
$count_cd34f4bae8c3c39484c552d071584aba = is_array($this->functionData['searchRowGenericFormat']) ? count($this->functionData['searchRowGenericFormat']) : 0;
$this->functionData['searchRowGenericFormat'][$count_cd34f4bae8c3c39484c552d071584aba]['r'] = $r;
$this->functionData['searchRowGenericFormat'][$count_cd34f4bae8c3c39484c552d071584aba]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topicPostSearchResultAsForum --*/
function topicPostSearchResultAsForum($data, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['topicPostSearchResultAsForum'] ) )
{
$count_651ab4daa2c69ad642e5cf4ae852437d = is_array($this->functionData['topicPostSearchResultAsForum']) ? count($this->functionData['topicPostSearchResultAsForum']) : 0;
$this->functionData['topicPostSearchResultAsForum'][$count_651ab4daa2c69ad642e5cf4ae852437d]['data'] = $data;
$this->functionData['topicPostSearchResultAsForum'][$count_651ab4daa2c69ad642e5cf4ae852437d]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'asForumTopics' ) ? $this->registry->getClass('output')->getTemplate('search')->asForumTopics($data) : '' ) . "";
return $IPBHTML;
}

/* -- userPostsView --*/
function userPostsView($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['userPostsView'] ) )
{
$count_6481530b1ebcbde283a923c855b2f8cc = is_array($this->functionData['userPostsView']) ? count($this->functionData['userPostsView']) : 0;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['results'] = $results;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['pagination'] = $pagination;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['total'] = $total;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['member'] = $member;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['limited'] = $limited;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['wasLimited'] = $wasLimited;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['beginTime'] = $beginTime;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['sortIn'] = $sortIn;
$this->functionData['userPostsView'][$count_6481530b1ebcbde283a923c855b2f8cc]['sortDropDown'] = $sortDropDown;
}
$IPBHTML .= "test
<pagination>{$pagination}</pagination>
{$results}";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>