<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 08 May 2013 03:43:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_help_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['helpShowSection'] = array('notajax','isajax','notajax');
$this->_funcHooks['helpShowTopics'] = array('helpfiles');


}

/* -- helpShowSection --*/
function helpShowSection($one_text="",$two_text="",$three_text="", $text) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_help', $this->_funcHooks['helpShowSection'] ) )
{
$count_f1c9f725ea9fe9c47edd29605ddcfb2d = is_array($this->functionData['helpShowSection']) ? count($this->functionData['helpShowSection']) : 0;
$this->functionData['helpShowSection'][$count_f1c9f725ea9fe9c47edd29605ddcfb2d]['one_text'] = $one_text;
$this->functionData['helpShowSection'][$count_f1c9f725ea9fe9c47edd29605ddcfb2d]['two_text'] = $two_text;
$this->functionData['helpShowSection'][$count_f1c9f725ea9fe9c47edd29605ddcfb2d]['three_text'] = $three_text;
$this->functionData['helpShowSection'][$count_f1c9f725ea9fe9c47edd29605ddcfb2d]['text'] = $text;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- helpShowTopics --*/
function helpShowTopics($one_text="",$two_text="",$three_text="",$rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_help', $this->_funcHooks['helpShowTopics'] ) )
{
$count_1a2e000192b43fa688b5a72bc4031ddd = is_array($this->functionData['helpShowTopics']) ? count($this->functionData['helpShowTopics']) : 0;
$this->functionData['helpShowTopics'][$count_1a2e000192b43fa688b5a72bc4031ddd]['one_text'] = $one_text;
$this->functionData['helpShowTopics'][$count_1a2e000192b43fa688b5a72bc4031ddd]['two_text'] = $two_text;
$this->functionData['helpShowTopics'][$count_1a2e000192b43fa688b5a72bc4031ddd]['three_text'] = $three_text;
$this->functionData['helpShowTopics'][$count_1a2e000192b43fa688b5a72bc4031ddd]['rows'] = $rows;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>