<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 08 May 2013 03:43:51 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_editors_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['ajaxEditBox'] = array('jsNotLoaded','ajaxerror','forceStd','showreason','appendedit','showappendedit','htmlstatus','showeditoptions');
$this->_funcHooks['editor'] = array('hasWrningInfo','jsNotLoaded','ismini','ismini','hasContent','hasType','ismini','hasHeight','hasMinimize','hasCallback','hasSaveKey','showEditor','hasToAcknowledge');
$this->_funcHooks['editorLoadJs'] = array('bypassCkEditor','hasimages','hasPastePlain');
$this->_funcHooks['mediaGenericWrapper'] = array('haswidth','hasheight','hasimage','hasdescription','genericmedia','hasrows');
$this->_funcHooks['sharedMedia'] = array('mediatabs');


}

/* -- ajaxEditBox --*/
function ajaxEditBox($post="", $pid=0, $error_msg="", $extraData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['ajaxEditBox'] ) )
{
$count_3739d59fe645bbb3739ccfd218536c3a = is_array($this->functionData['ajaxEditBox']) ? count($this->functionData['ajaxEditBox']) : 0;
$this->functionData['ajaxEditBox'][$count_3739d59fe645bbb3739ccfd218536c3a]['post'] = $post;
$this->functionData['ajaxEditBox'][$count_3739d59fe645bbb3739ccfd218536c3a]['pid'] = $pid;
$this->functionData['ajaxEditBox'][$count_3739d59fe645bbb3739ccfd218536c3a]['error_msg'] = $error_msg;
$this->functionData['ajaxEditBox'][$count_3739d59fe645bbb3739ccfd218536c3a]['extraData'] = $extraData;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editor --*/
function editor($formField='post', $content='', $options=array(), $autoSaveData=array(), $warningInfo='', $acknowledge=FALSE) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['editor'] ) )
{
$count_0cfd482d9dfc39f90fad5ee9406be3bf = is_array($this->functionData['editor']) ? count($this->functionData['editor']) : 0;
$this->functionData['editor'][$count_0cfd482d9dfc39f90fad5ee9406be3bf]['formField'] = $formField;
$this->functionData['editor'][$count_0cfd482d9dfc39f90fad5ee9406be3bf]['content'] = $content;
$this->functionData['editor'][$count_0cfd482d9dfc39f90fad5ee9406be3bf]['options'] = $options;
$this->functionData['editor'][$count_0cfd482d9dfc39f90fad5ee9406be3bf]['autoSaveData'] = $autoSaveData;
$this->functionData['editor'][$count_0cfd482d9dfc39f90fad5ee9406be3bf]['warningInfo'] = $warningInfo;
$this->functionData['editor'][$count_0cfd482d9dfc39f90fad5ee9406be3bf]['acknowledge'] = $acknowledge;
}
$IPBHTML .= "<content><![CDATA[{$content}]]></content>";
return $IPBHTML;
}

/* -- editorLoadJs --*/
function editorLoadJs($options='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['editorLoadJs'] ) )
{
$count_4b3492edd5b0b0351a8336cc702fe090 = is_array($this->functionData['editorLoadJs']) ? count($this->functionData['editorLoadJs']) : 0;
$this->functionData['editorLoadJs'][$count_4b3492edd5b0b0351a8336cc702fe090]['options'] = $options;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editorSettings --*/
function editorSettings() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mediaGenericWrapper --*/
function mediaGenericWrapper($rows, $pages, $app, $plugin) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['mediaGenericWrapper'] ) )
{
$count_e4f1b4489e0f851a683ff2a00464fa12 = is_array($this->functionData['mediaGenericWrapper']) ? count($this->functionData['mediaGenericWrapper']) : 0;
$this->functionData['mediaGenericWrapper'][$count_e4f1b4489e0f851a683ff2a00464fa12]['rows'] = $rows;
$this->functionData['mediaGenericWrapper'][$count_e4f1b4489e0f851a683ff2a00464fa12]['pages'] = $pages;
$this->functionData['mediaGenericWrapper'][$count_e4f1b4489e0f851a683ff2a00464fa12]['app'] = $app;
$this->functionData['mediaGenericWrapper'][$count_e4f1b4489e0f851a683ff2a00464fa12]['plugin'] = $plugin;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- sharedMedia --*/
function sharedMedia($tabs) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['sharedMedia'] ) )
{
$count_9acd4815a0d1135b7c11f3d9b9757061 = is_array($this->functionData['sharedMedia']) ? count($this->functionData['sharedMedia']) : 0;
$this->functionData['sharedMedia'][$count_9acd4815a0d1135b7c11f3d9b9757061]['tabs'] = $tabs;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- sharedMediaDefault --*/
function sharedMediaDefault() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>