<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 4               */
/* CACHE FILE: Generated: Fri, 07 Jun 2013 18:02:06 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_boards_4 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['boardIndexTemplate'] = array('showSubForumsLit','subforums','canSeeLastInfoRedirect','hasUnreadClass','hasUnread','hasQueuedAndCanSeeIcon','showSubForums','hideTopicInTitle','hideDateUrl','lastPosterID','hideLastInfo','canSeeLastInfo','forumRedirect','forums','canSeeLastInfoHeader','cat_has_forums','categories','side_blocks','markerhasunread','markernotredirect','markerforums','markerhasforums','markercategories','boardIndexTop','sideBarEnabledL','sidebarclosed','cats_forums','sidebarclosed2','sideBarEnabled2','markercatforums','showTotals','reputationType','reputationEnabled','statsLinks','showActive','onlineListEnabled','activeNames');
$this->_funcHooks['hookFacebookActivity'] = array('fbAppIdPresent');
$this->_funcHooks['hookGroupNameIndicator'] = array('showGroupNameIndicator');
$this->_funcHooks['hookRecentTopics'] = array('topics_hook','recenttopics');
$this->_funcHooks['hookTagCloud'] = array('eachTag');
$this->_funcHooks['statusReplies'] = array('canDelete','isFirstCycle','innerLoop');
$this->_funcHooks['statusUpdates'] = array('canDelete','isLocked','canLock','noLocked','cImg','hasRepliesMain','hasRepliesButCannotReply','canReplyMain','hasMore','hasReplies','canReply','outerLoop');


}

/* -- boardIndexTemplate --*/
function boardIndexTemplate($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['boardIndexTemplate'] ) )
{
$count_4dcc5819a2ad5c666a531f53726365bd = is_array($this->functionData['boardIndexTemplate']) ? count($this->functionData['boardIndexTemplate']) : 0;
$this->functionData['boardIndexTemplate'][$count_4dcc5819a2ad5c666a531f53726365bd]['lastvisit'] = $lastvisit;
$this->functionData['boardIndexTemplate'][$count_4dcc5819a2ad5c666a531f53726365bd]['stats'] = $stats;
$this->functionData['boardIndexTemplate'][$count_4dcc5819a2ad5c666a531f53726365bd]['cat_data'] = $cat_data;
$this->functionData['boardIndexTemplate'][$count_4dcc5819a2ad5c666a531f53726365bd]['show_side_blocks'] = $show_side_blocks;
$this->functionData['boardIndexTemplate'][$count_4dcc5819a2ad5c666a531f53726365bd]['side_blocks'] = $side_blocks;
}

$this->templateVars['sidebar_enabled'] = "$show_side_blocks";
$this->__default__templateVars['sidebar_enabled'] = "$show_side_blocks";
$IPBHTML .= "" . (($this->settings['hoverDescriptions']='yes') ? ("") : ("")) . "
" . (($this->settings['removeStatsColumn']='yes') ? ("") : ("")) . "
" . (($this->settings['customForumIcons']='no') ? ("") : ("")) . "
<!-- -->

<!--IBF.NEWPMBOX-->
<style type='text/css'>
						.globalmesswarnwrap{
					background:url('http://kuller.su/public/style_images/uniform/background4.jpg');
							border: 1px solid #353529;
							border-top: 0;
							margin: 10px 0 0 0;
							padding: 0;
						}

						.globalmesswarnwrap h4{
							background: #625b44;
							border: 1px solid #353529;
							border-left: 0;
							border-right: 0;
							color: #ffeee2;
							font-size: 12px;
							font-weight: bold;
							padding: 5px;
						}

						.globalmesswarncontent{
							background: transparent;
							border: 0;
							color: #ffeee2;
							margin: 0;
							padding: 8px;
						}

						.globalmesswarncontent a:link,
						.globalmesswarncontent a:visited,
						.globalmesswarncontent a:active{
							background: transparent;
							text-decoration: underline;
							color: #ffeee2;
						}

						.globalmesswarncontent a:hover{
							background: transparent;
							text-decoration: underline;
							color: #ffbc7f;
						}
						</style><div class='globalmesswarnwrap'><div class='globalmesswarncontent'>
<table width=\"100%\" style=\"margin:10px\"><tr><td align=left>
<span style=\"padding:0px 30px;\"></span><object id=\"youtubeColorRu\" width=\"350\" height=\"250\"><param name=\"movie\" value=\"http://www.youtube.com/v/APtyfZD2OX4?version=2&color1=0x000000&color2=0xFFFFFF&border=1&egm=1&rel=0&showinfo=0&showsearch=0\"></param><param name=\"allowFullScreen\" value=\"true\"></param><param name=\"allowscriptaccess\" value=\"always\"></param><embed src=\"http://www.youtube.com/v/APtyfZD2OX4?version=2&color1=0x000000&color2=0xFFFFFF&border=1&egm=1&rel=0&showinfo=0&showsearch=0\" type=\"application/x-shockwave-flash\" width=\"350\" height=\"250\" allowscriptaccess=\"always\" allowfullscreen=\"true\" ></embed></object>
<td align=center>
<a href=\"http://kuller.su/index.php?/forum/12-tekhnicheskii-razdel/\" target=\"_blank\"><img src=\"http://kuller.su/files/technical.png\"></a><br>

<a href=\"http://kuller.su/index.php?/forum/12-tekhnicheskii-razdel/\" target=\"_blank\"><font color=\"#ffffff\"><b>Техническая поддержка</b></font></a><br>

<a href=\"http://kuller.su/index.php?/topic/45-pravila-servera/\" target=\"_blank\"><img src=\"http://kuller.su/files/pravila.png\"></a><br>

<a href=\"http://kuller.su/index.php?/topic/45-pravila-servera/\" target=\"_blank\"><font color=\"#ffffff\"><b>Правила игры</b></font></a></td>
<td align=center>
<a href=\"http://kuller.su/index.php?/topic/47-kak-uberech-akkaunt-ot-vzloma/\" target=\"_blank\"><img src=\"http://kuller.su/files/protect.png\"></a><br>

<a href=\"http://kuller.su/index.php?/topic/47-kak-uberech-akkaunt-ot-vzloma/\" target=\"_blank\"><font color=\"#ffffff\"><b>Безопасность аккаунта</b></font></a><br>

<a href=\"http://kuller.su/topic/88-kak-priobresti-rub-na-servere/\" target=\"_blank\"><img src=\"http://kuller.su/files/donat.png\"></a><br>

<a href=\"http://kuller.su/index.php?/topic/52-kupit-rub/\" target=\"_blank\"><font color=\"#ffffff\"><b>Игровой магазин</b></font></a></td>
<td align=center>
<a href=\"http://kuller.su/index.php?/forum/16-pomosch/\" target=\"_blank\"><img src=\"http://kuller.su/files/ingame.png\"></a><br>

<a href=\"http://kuller.su/index.php?/forum/16-pomosch/\" target=\"_blank\"><font color=\"#ffffff\"><b>Внутриигровые вопросы</b></font></a><br>

<a href=\"http://kuller.su/index.php?/forum/13-priyomnaia/\" target=\"_blank\"><img src=\"http://kuller.su/files/priem.png\"></a><br>

<a href=\"http://kuller.su/index.php?/forum/13-priyomnaia/\" target=\"_blank\"><font color=\"#ffffff\"><b>Приёмная</b></font></a></td>
</tr></table></div></div>
<span style=\"padding:0px 10px;\"></span>
<h3 class='maintitle'>




<center>KulleR.su | Zombie [RUS/ENG] — <a href=\"samp://77.220.175.4:7797\" title=\"Подключиться\" style=\"color:red\"> 77.220.175.4:7797</a></center>




</h3>








<div class='ipsBox table_wrap'><div class='ipsBox_container'>




</div>




<br />


" . $this->registry->getClass('output')->addJSModule("board", "0" ) . "" . ((true) ? ("") : ("")) . "
<div id='board_index' class='ipsLayout " . (($this->templateVars['sidebar_enabled']) ? ("ipsLayout_withright") : ("")) . " ipsLayout_largeright clearfix " . ((IPSCookie::get('hide_sidebar') == '1') ? ("no_sidebar") : ("")) . "'>	
	<div id='categories' class='ipsLayout_content clearfix'>
	<!-- CATS AND FORUMS -->
		" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
			".$this->__f__207a86f51f1c6a6e140902e770489fe8($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."		") : ("")) . "
	</div>
	" . (($this->templateVars['sidebar_enabled']) ? ("<div id='index_stats' class='ipsLayout_right clearfix' " . ((IPSCookie::get('hide_sidebar') == '1') ? ("style='display: none'") : ("")) . ">


			".$this->__f__2709016272ba1f9f489e8d7b578ce521($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."<!-- СЧЁТЧИКИ НАЧАЛО -->
<div class='ipsSideBlock clearfix'>
	<h3>Счётчики</h3>
	<div class='_sbcollapsable'>
<ul class='ipsList_inline left'><li> <!--LiveInternet counter--><script type=\"text/javascript\"><!--
document.write(\"<a href='http://www.liveinternet.ru/click' \"+
\"target=_blank><img src='//counter.yadro.ru/hit?t22.4;r\"+
escape(document.referrer)+((typeof(screen)==\"undefined\")?\"\":
\";s\"+screen.width+\"*\"+screen.height+\"*\"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+\";u\"+escape(document.URL)+
\";\"+Math.random()+
\"' alt='' title='LiveInternet: показано число просмотров за 24\"+
\" часа, посетителей за 24 часа и за сегодня' \"+
\"border='0' width='88' height='31'><\\/a>\")
//--></script><!--/LiveInternet--></li><li> 			<!-- Rating@Mail.ru counter -->
<script type=\"text/javascript\">//<![CDATA[
(function(w,n,d,r,s){d.write('<div><a href=\"http://top.mail.ru/jump?from=2354878\"><img src=\"'+
('https:'==d.location.protocol?'https:':'http:')+'//top-fwz1.mail.ru/counter?id=2354878;t=210;js=13'+
((r=d.referrer)?';r='+escape(r):'')+((s=w.screen)?';s='+s.width+'*'+s.height:'')+';_='+Math.random()+
'\" style=\"border:0;\" height=\"31\" width=\"88\" alt=\"Рейтинг@Mail.ru\" /><\\/a><\\/div>');})(window,navigator,document);//]]>
</script><noscript><div><a href=\"http://top.mail.ru/jump?from=2354878\">
<img src=\"//top-fwz1.mail.ru/counter?id=2354878;t=210;js=na\" style=\"border:0;\"
height=\"31\" width=\"88\" alt=\"Рейтинг@Mail.ru\" /></a></div></noscript>
<!-- //Rating@Mail.ru counter --></li></ul>

<ul class='ipsList_inline left'><li> <!-- begin of Top100 code -->
<br></br>
<script id=\"top100Counter\" type=\"text/javascript\" src=\"http://counter.rambler.ru/top100.jcn?2901599\"></script>
<noscript>
<a href=\"http://top100.rambler.ru/navi/2901599/\">
<img src=\"http://counter.rambler.ru/top100.cnt?2901599\" alt=\"Rambler's Top100\" border=\"0\" />
</a>

</noscript>
<!-- end of Top100 code --></li><li>           <!-- Rank.Ru - рейтинг популярности ресурсов РуНета , code for http://kuller.su -->
          <script type=\"text/javascript\">java=\"1.0\";java1=\"\"+\"refer=\"+escape(document.referrer)+\"&page=\"+escape(window.location.href); document.cookie=\"astratop=1; path=/\"; java1+=\"&c=\"+(document.cookie?\"yes\":\"now\");</script>
          <script type=\"text/javascript1.1\">java=\"1.1\";java1+=\"&java=\"+(navigator.javaEnabled()?\"yes\":\"now\")</script>
          <script type=\"text/javascript1.2\">java=\"1.2\";java1+=\"&razresh=\"+screen.width+'x'+screen.height+\"&cvet=\"+(((navigator.appName.substring(0,3)==\"Mic\"))? screen.colorDepth:screen.pixelDepth)</script>
          <script type=\"text/javascript1.3\">java=\"1.3\"</script>
          <script type=\"text/javascript\">java1+=\"&jscript=\"+java+\"&rand=\"+Math.random(); document.write(\"<a href='http://rank.ru/?fromsite=358'><img \"+\" src='http://rank.ru/img.php?id=358&\"+java1+\"&' border='0' alt='Rank.Ru - рейтинг популярности ресурсов РуНета' width='88' height='31'><\\/a>\");</script>
          <noscript><a href=\"http://rank.ru/?fromsite=358\" target=\"_blank\"><img src=\"http://rank.ru/img.php?id=358\" border=\"0\" alt=\"Rank.Ru - рейтинг популярности ресурсов РуНета\" width=\"88\" height=\"31\"></a></noscript>
          <!-- /Rank.Ru - рейтинг популярности ресурсов РуНета -->
      </li></ul>



<ul class='ipsList_inline left'><li>
<br></br> <!-- InetLog -->
<script language=\"javascript\">
i=Math.random();w=screen.width;h=screen.height;
clr=screen.colorDepth;
if(navigator.cookieEnabled) ck = \"Y\"; else ck = \"N\";
document.write('<a href=\"http://inetlog.ru/\" target=\"_top\"><img width=88 height=31 src=\"http://inetlog.ru/counter/?i='+i+'&cid=49&r='+escape(document.referrer)+'&sid=59395&ck='+ck+'&res='+w+'x'+h+'&clr='+clr+'&pg='+escape(window.location.href)+'\" alt=\"InetLog.ru - статистика сайта\" border=0></a>')
</script><a href=\"http://inetlog.ru\" title=\"статистика\"><img border=0 width=1 height=1 src=\"http://inetlog.ru/img/del.gif\" alt=\"статистика\"></a>
<!-- /InetLog --></li><li> <!-- HotLog -->
<script type=\"text/javascript\">
hotlog_r=\"\"+Math.random()+\"&s=2297473&im=457&r=\"+
escape(document.referrer)+\"&pg=\"+escape(window.location.href);
hotlog_r+=\"&j=\"+(navigator.javaEnabled()?\"Y\":\"N\");
hotlog_r+=\"&wh=\"+screen.width+\"x\"+screen.height+\"&px=\"+
(((navigator.appName.substring(0,3)==\"Mic\"))?screen.colorDepth:screen.pixelDepth);
hotlog_r+=\"&js=1.3\";
document.write('<a href=\"http://click.hotlog.ru/?2297473\" target=\"_blank\"><img '+
'src=\"http://hit3.hotlog.ru/cgi-bin/hotlog/count?'+
hotlog_r+'\" border=\"0\" width=\"88\" height=\"31\" title=\"HotLog: показано количество посетителей за сегодня и всего\" alt=\"HotLog\"><\\/a>');
</script>
<noscript>
<a href=\"http://click.hotlog.ru/?2297473\" target=\"_blank\"><img
src=\"http://hit3.hotlog.ru/cgi-bin/hotlog/count?s=2297473&im=457\" border=\"0\"
width=\"88\" height=\"31\" title=\"HotLog: показано количество посетителей за сегодня и всего\" alt=\"HotLog\"></a>
</noscript>
<!-- /HotLog --></li></ul>
<ul class='ipsList_inline left'><li>
<br></br>
<!-- Yandex.Metrika informer -->
<a href=\"http://metrika.yandex.ru/stat/?id=21361102&amp;from=informer\"
target=\"_blank\" rel=\"nofollow\"><img src=\"//bs.yandex.ru/informer/21361102/3_0_FFFFFFFF_FAF0E6FF_0_pageviews\"
style=\"width:88px; height:31px; border:0;\" alt=\"Яндекс.Метрика\" title=\"Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)\" onclick=\"try{Ya.Metrika.informer({i:this,id:21361102,lang:'ru'});return false}catch(e){}\"/></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type=\"text/javascript\">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter21361102 = new Ya.Metrika({id:21361102,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName(\"script\")[0],
        s = d.createElement(\"script\"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = \"text/javascript\";
    s.async = true;
    s.src = (d.location.protocol == \"https:\" ? \"https:\" : \"http:\") + \"//mc.yandex.ru/metrika/watch.js\";

    if (w.opera == \"[object Opera]\") {
        d.addEventListener(\"DOMContentLoaded\", f, false);
    } else { f(); }
})(document, window, \"yandex_metrika_callbacks\");
</script>
<noscript><div><img src=\"//mc.yandex.ru/watch/21361102\" style=\"position:absolute; left:-9999px;\" alt=\"\" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</li>
<li>
<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"88\" height=\"31\" style=\"line-height:0;width:88px;\"><tr style=\"height:10px;\">
<td style=\"padding:0;width:38px;height:10px;\"><a href=\"http://www.24log.de\" target=\"_blank\"><img src=\"http://counter.24log.ru/buttons/24/bg24-4_1.gif\" width=\"38\" height=\"10\" border=\"0\" alt=\"Besucherzahler\" title=\"Besucherzahler \" style=\"margin:0;padding:0;\" /></a></td>
<td style=\"padding:0;width:50px;height:10px;\"><a href=\"http://www.russianwoman.ca\" target=\"_blank\"><img src=\"http://counter.24log.ru/buttons/24/bg24-4_3.gif\" width=\"50\" height=\"10\" border=\"0\" alt=\"russian brides\" style=\"margin:0;padding:0;\"></a></td></tr>
<tr style=\"height:21px;\"><td style=\"padding:0;width:38px;height:21px\"><a href=\"http://www.24log.ru\" target=\"_blank\"><img src=\"http://counter.24log.ru/buttons/24/bg24-4_2.gif\" width=\"38\" height=\"21\" alt=\"счетчик посещений\" title=\"счетчик посещений\" border=\"0\" style=\"margin:0;padding:0;\" /></a></td>
<script type='text/javascript' language='javascript'>
document.write('<td style=\"padding:0px;width:50px;height:21px;\"><a href=\"http://www.24log.ru/rating/rating.php?c=12\" target=\"_blank\"><img border=\"0\" width=\"50\" height=\"21\" src=\"http://counter.24log.ru/counter?id=210872&t=24&st=4&r='+escape(document.referrer)+'&u='+escape(document.URL)+'&s='+((typeof(screen)=='undefined')?'':screen.width+'x'+screen.height+'x'+(screen.colorDepth?screen.colorDepth:screen.pixelDepth))+'&rnd='+Math.random()+'\" alt=\"Рейтинг: Развлечения\" title=\"Показано число просмотров всего и за сегодня\" style=\"margin:0;padding:0;\" /></a></td>');
</script></tr></table><NOSCRIPT><a href=\"http://www.1russianbrides.com\">Foreign brides from Russia</a></NOSCRIPT>
</li>
</ul>

	</div>
</div>





<!-- СЧЁТЧИКИ КОНЕЦ -->
		</div>
		<a href='#' id='toggle_sidebar' title='{$this->lang->words['toggle_sidebar']}' data-closed=\"{$this->lang->words['_laquo']}\" data-open=\"&times;\">&nbsp;</a>") : ("")) . "
</div>
<h3 class='maintitle'>

<center>KulleR.su | Zombie [RUS/ENG] — <a href=\"samp://77.220.175.4:7797\" title=\"Подключиться\" style=\"color:red\"> 77.220.175.4:7797</a></center>

</h3>


<div class='ipsBox table_wrap'><div class='ipsBox_container'>

</div>

<br />
<script type='text/javascript'>
//<![CDATA[
	var markerURL  = ipb.vars['base_url'] + \"app=forums&module=ajax&section=markasread&i=1\"; // Ajax URL so don't use &amp;
	var unreadIcon = \"<img src='{$this->settings['img_url']}/f_icon_read.png' />\";
	
	" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
		".$this->__f__f8f48f749116c42efd057b00fa0264cb($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."	") : ("")) . "
//]]>
</script>
" . (($this->settings['show_totals']) ? ("
	<div id='board_stats'>		
		<ul class='ipsType_small ipsList_inline'>
			<li class='clear'>
				<span class='value'>{$stats['info']['total_posts']}</span>
				{$this->lang->words['total_posts']}
			</li>
			<li class='clear'>
				<span class='value'>{$stats['info']['mem_count']}</span>
				{$this->lang->words['total_members']}
			</li>
			<li class='clear'>
				" . IPSMember::makeProfileLink( $stats['info']['last_mem_name'], $stats['info']['last_mem_id'], $stats['info']['last_mem_seo'], 'value' ) . "
				{$this->lang->words['newest_member']}
			</li>
			<li class='clear' data-tooltip=\"{$stats['info']['most_time']}\">
				<span class='value'>{$stats['info']['most_online']}</span>
				{$this->lang->words['online_at_once']}
			</li>
		</ul>
	</div>
") : ("")) . "
<div id='board_statistics' class='statistics clearfix'>
	<h4 class='statistics_head clearfix'><ul id='stat_links' class='ipsList_inline right ipsType_small'>
		" . ((1==1) ? ("<!-- Hook point -->
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats&amp;do=leaders", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['sm_forum_leaders_title']}\">{$this->lang->words['sm_forum_leaders']}</a></li>
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['sm_all_posters_title']}\">{$this->lang->words['sm_today_posters']}</a></li>
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;max_results=20&amp;sort_key=posts&amp;sort_order=desc&amp;filter=ALL", "public",'' ), "false", "" ) . "\" title=\"{$this->lang->words['sm_overall_posters_title']}\">{$this->lang->words['sm_overall_posters']}</a></li>
            " . (($this->settings['reputation_enabled']) ? ("<li>
                    <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=reputation&amp;section=most", "public",'' ), "most_liked", "most_liked" ) . "\">
                        " . (($this->settings['reputation_point_types'] == 'like') ? ("
                            {$this->lang->words['most_rep_likes']}
                        ") : ("
                            {$this->lang->words['most_rep_rep']}
                        ")) . "
                    </a>
                </li>") : ("")) . "<!--hook.if.skin_boards.boardIndexTemplate.statsLinks.pre.endif-->") : ("")) . "
	</ul>
" . (($this->settings['show_active'] && $this->memberData['gbw_view_online_lists']) ? ("" . sprintf( $this->lang->words['online_right_now'], $stats['TOTAL'] ) . " {$this->lang->words['active_users']}") : ("")) . "</h4>
	" . (($this->settings['show_active']) ? ("<p class='statistics_brief desc'>
		" . sprintf( $this->lang->words['active_users_detail'], $stats['MEMBERS'], $stats['GUESTS'], $stats['ANON'] ) . "
		" . (($this->settings['allow_online_list']) ? ("&nbsp;&nbsp;<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=online&amp;sort_order=desc", "public",'' ), "", "" ) . "'>({$this->lang->words['online_link']})</a> ") : ("")) . "
	</p>") : ("")) . "
	
	" . ((count($stats['NAMES']) && $this->settings['show_active']) ? ("
		<br />
		<p>
			<span class='name'>" . implode( ",</span> <span class='name'>", $stats['NAMES'] ) . "</span>					
		</p>
	") : ("")) . "<!--hook.if.skin_boards.boardIndexTemplate.activeNames.post.endif-->
</div>";
return $IPBHTML;
}


function __f__165661c2acd468f1c22c887253e01087($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='',$forum_id='',$forum_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $forum_data['subforums'] as $__id => $__data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
																" . (($__data[3]) ? ("<li class='unread'>") : ("<li>")) . "
																	<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$__data[0]}", "public",'' ), "{$__data[2]}", "showforum" ) . "\" title='{$this->lang->words['go_to_forum']}'>{$__data[1]}</a>
																</li>
															
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__5b56a590fd1e627466dba87083f10ee0($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
$imageURL = "{$this->settings['img_url']}";
															$imageFolder = basename($imageURL);
															$forumId = $forum_data['id'];

$imageURL = "{$this->settings['img_url']}";
																$imageFolder = basename($imageURL);
																$forumId = $forum_data['id'];

$imageURL = "{$this->settings['img_url']}";
																$imageFolder = basename($imageURL);
																$forumId = $forum_data['id'];

		$__iteratorCount++;
		$_ips___x_retval .= "
										" . (($forum_data['redirect_on']) ? ("<tr class='redirect_forum' id='f_{$forum_data['id']}'>
												<td class='col_c_icon'>
													" . (($this->settings['customForumIcons']=='yes') ? ("														" . ((is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_images/' . $imageFolder . '/forum_images/' . $forumId . '.png' )) ? ("
															<img src=\"{style_images_url}/forum_images/{$forum_data['id']}.png\" alt=\"\" />
														") : ("
															<img src=\"{style_images_url}/forum_images/default.png\" alt=\"\" />
														")) . "") : ("
														<img src='{$this->settings['img_url']}/f_redirect.png' />
													")) . "
												</td>
												<td " . (($this->settings['removeStatsColumn']=='no') ? ("" . (($this->memberData['gbw_view_last_info']) ? ("colspan='2'") : ("")) . "") : ("")) . " class='col_c_forum'>
													<h4 class='forum_name'><strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$forum_data['name']}'>{$forum_data['name']}</a></strong></h4>
													" . (($forum_data['description']) ? ("" . (($this->settings['hoverDescriptions']=='yes') ? ("<span class='forum_desc_pos'><span class='forum_desc_con'><span class='forum_description'>{$forum_data['description']}</span></span></span>") : ("<p class='desc forum_desc'>{$forum_data['description']}</p>")) . "") : ("")) . "
												</td>
												<td class='desc'>
													<ul class='last_post ipsType_small'>
                                                        							<li class='desc lighter'><em>" . $this->registry->getClass('class_localization')->formatNumber( $forum_data['redirect_hits'] ) . " {$this->lang->words['rd_hits']}</em></li>
                                                    							</ul>
												</td>
											</tr>") : ("<tr class='" . (($forum_data['_has_unread']) ? ("unread") : ("notnew")) . "'>
												<td class='col_c_icon'>
													" . (($forum_data['_has_unread']) ? ("<a id='forum_img_{$forum_data['id']}' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=forum&amp;forumid={$forum_data['id']}&amp;returntoforumid={$this->request['f']}&amp;i=1", "public",'' ), "", "" ) . "\" data-tooltip=\"{$this->lang->words['bi_markread']}\" class='forum_marker'>													
														" . (($this->settings['customForumIcons']=='yes') ? ("															" . ((is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_images/' . $imageFolder . '/forum_images/' . $forumId . '.png' )) ? ("
																<img src=\"{style_images_url}/forum_images/{$forum_data['id']}.png\" alt=\"\" />
															") : ("
																<img src=\"{style_images_url}/forum_images/default.png\" alt=\"\" />
															")) . "") : ("
															<img src='{$this->settings['img_url']}/f_icon.png' />
														")) . "
														</a>") : ("" . (($this->settings['customForumIcons']=='yes') ? ("															" . ((is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_images/' . $imageFolder . '/forum_images/' . $forumId . '.png' )) ? ("
																<img src=\"{style_images_url}/forum_images/{$forum_data['id']}.png\" alt=\"\" class='fadedForumIcon' />
															") : ("
																<img src=\"{style_images_url}/forum_images/default.png\" alt=\"\" class='fadedForumIcon' />
															")) . "") : ("
															<img src='{$this->settings['img_url']}/f_icon_read.png' />
														")) . "")) . "
												</td>
												<td class='col_c_forum'>
													
													<h4 class='forum_name'>
														" . ((!empty($forum_data['_has_queued_and_can_see_icon'])) ? ("
															<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}&amp;modfilter=unapproved", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "' title='{$this->lang->words['view_unapproved']}' class='ipsBadge ipsBadge_orange' data-tooltip=\"" . sprintf( $this->lang->words['f_queued'], $forum_data['queued_topics'], $forum_data['queued_posts']) . "\" style='vertical-align: top'>{$this->lang->words['f_queued_badge']}</a>
														") : ("")) . "
														<strong class='highlight_unread'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$forum_data['name']}'>{$forum_data['name']}</a></strong>
													</h4>

													" . (($forum_data['description']) ? ("" . (($this->settings['hoverDescriptions']=='yes') ? ("<span class='forum_desc_pos'><span class='forum_desc_con'><span class='forum_description'>{$forum_data['description']}</span></span></span>") : ("<p class='desc forum_desc'>{$forum_data['description']}</p>")) . "") : ("")) . "
" . (($this->settings['removeStatsColumn']=='yes') ? ("<div class='forum_stats'><span>{$this->lang->words['topics']}:</span> {$forum_data['topics']}  &nbsp; <span>{$this->lang->words['replies']}:</span> {$forum_data['posts']}</div>") : ("")) . "	

													" . (($forum_data['show_subforums'] AND count( $forum_data['subforums'] ) AND $forum_data['show_subforums']) ? ("
														<ol class='ipsList_inline ipsType_small subforums' id='subforums_{$forum_data['id']}'>
															".$this->__f__165661c2acd468f1c22c887253e01087($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data,$forum_id,$forum_data)."														</ol>
													") : ("")) . "
																					
												</td>
												" . (($this->settings['removeStatsColumn']=='no') ? ("<td class='col_c_stats ipsType_small'>
													<ul>
														<li>{$forum_data['topics']} {$this->lang->words['topics']}</li>
														<li>{$forum_data['posts']} {$this->lang->words['replies']}</li>
													</ul>
												</td>") : ("")) . "
                                                " . (($this->memberData['gbw_view_last_info']) ? ("<td class='col_c_post'>
													" . (($forum_data['hide_last_info']) ? ("
														<ul class='last_post'>
															<li class='desc lighter'><em>{$this->lang->words['f_protected']}</em></li>
														</ul>
													") : ("" . (($forum_data['_hide_last_date']) ? ("
                                                        " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array('member_id' => $forum_data['last_poster_id'], 'members_seo_name' => $forum_data['seo_last_name'], 'pp_small_photo' => $forum_data['pp_small_photo'], 'alt' => '' )) : '' ) . "
                                                        ") : ("
														" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array('member_id' => $forum_data['last_poster_id'], 'members_seo_name' => $forum_data['seo_last_name'], 'pp_small_photo' => $forum_data['pp_small_photo'], 'alt' => sprintf( $this->lang->words['bindex_userphoto_alt'], $forum_data['last_title'], $forum_data['members_display_name'] ) )) : '' ) . "
")) . "
														<ul class='last_post ipsType_small'>
															" . ((!$forum_data['last_id']) ? ("
																<li class='desc lighter'><em>{$this->lang->words['f_none']}</em></li>
															") : ("<li>
																	<span class='highlight_unread'>{$forum_data['last_topic_title']}</span>
																</li>
                                                                <li>
                                                                    <span class='desc lighter blend_links'>
                                                                    " . (($forum_data['_hide_last_date']) ? ("
                                                                        " . $this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0) . "
                                                                    ") : ("
                                                                        <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$forum_data['last_id']}&amp;view=getlastpost", "public",'' ), "{$forum_data['seo_last_title']}", "showtopic" ) . "' title='{$this->lang->words['view_last_post']}'>" . $this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0) . "</a>
                                                                    ")) . "</span>
                                                                    " . (($forum_data['last_poster_id']) ? ("
                                                                        {$this->lang->words['by']} " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($forum_data) : '' ) . "
                                                                    ") : ("")) . "
                                                                </li>")) . "
															
														</ul>")) . "
												</td>") : ("")) . "
											</tr>")) . "
									
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__207a86f51f1c6a6e140902e770489fe8($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("<div id='category_{$_data['cat_data']['id']}' class='category_block block_wrap'>
						" . $this->registry->getClass('output')->getReplacement("header_start") . "<h3 class='maintitle'>
							<a class='toggle right' href='#' title=\"" . sprintf( $this->lang->words['toggle_cat'], $_data['cat_data']['name'] ) . "\">" . sprintf( $this->lang->words['toggle_cat'], $_data['cat_data']['name'] ) . "</a> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$_data['cat_data']['id']}", "public",'' ), "{$_data['cat_data']['name_seo']}", "showforum" ) . "\" title='" . sprintf( $this->lang->words['view_cat'], $_data['cat_data']['name'] ) . "'>{$_data['cat_data']['name']}</a>
						</h3>" . $this->registry->getClass('output')->getReplacement("header_end") . "
						<div class='ipsBox table_wrap removeDefault'>
							<div class='ipsBox_container'>
								<table class='ipb_table' summary=\"{$this->lang->words['forums_in_cat']} '{$_data['cat_data']['name']}'\">
									<tr class='header hide'>
										<th scope='col' class='col_c_icon'>&nbsp;</th>
										<th scope='col' class='col_c_forum'>{$this->lang->words['cat_name']}</th>
										" . (($this->settings['removeStatsColumn']=='no') ? ("<th scope='col' class='col_c_stats stats'>{$this->lang->words['stats']}</th>") : ("")) . "
										" . (($this->memberData['gbw_view_last_info']) ? ("<th scope='col' class='col_c_post'>{$this->lang->words['last_post_info']}</th>") : ("")) . "
									</tr>
									<!-- / CAT HEADER -->
									".$this->__f__5b56a590fd1e627466dba87083f10ee0($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."								</table>
							</div>
						</div>" . $this->registry->getClass('output')->getReplacement("box_end") . "
						<br />
					</div>") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__2709016272ba1f9f489e8d7b578ce521($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '<!--hook.foreach.skin_boards.boardIndexTemplate.side_blocks.outer.pre-->';
	$__iteratorCount = 0;
	foreach( $side_blocks as $block )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				{$block}
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__315e439027eb03786a45468f05abe155($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . ((!$forum_data['redirect_on']) ? ("" . (($forum_data['_has_unread']) ? ("
	ipb.global.registerMarker( \"forum_img_{$forum_data['id']}\", \"{$forum_data['img_new_post']}\", markerURL + \"&forumid={$forum_data['id']}\" );
						") : ("")) . "") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__f8f48f749116c42efd057b00fa0264cb($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("
				".$this->__f__315e439027eb03786a45468f05abe155($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."			") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookBoardIndexStatusUpdates --*/
function hookBoardIndexStatusUpdates($updates=array()) {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript' src=\"{$this->settings['public_dir']}js/ips.status.js\"> </script>
<div class='ipsSideBlock clearfix' id='statusHook'>
	<h3>{$this->lang->words['recent_status_updates']}</h3>
	<div class='_sbcollapsable'>
		<div id=\"status_wrapper\">
			<div id=\"status_wrapper_inside\">" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'statusUpdates' ) ? $this->registry->getClass('output')->getTemplate('boards')->statusUpdates($updates, 1, 1) : '' ) . "</div>
			<div class=\"status_main_content ipsType_small\" style='text-align: center; margin: 10px -10px -10px -10px;'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=all", "public",'' ), "true", "members_status_all" ) . "' style='display: block; padding: 8px; font-weight: bold;'>{$this->lang->words['viewallupdates']}</a>
			</div>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- hookFacebookActivity --*/
function hookFacebookActivity() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookFacebookActivity'] ) )
{
$count_97a037d6994d361449ca172ca6bc8e35 = is_array($this->functionData['hookFacebookActivity']) ? count($this->functionData['hookFacebookActivity']) : 0;
}
$IPBHTML .= "" . ((IPSLib::fbc_enabled()) ? ("
<div class='general_box clearfix'>
	<h3>{$this->lang->words['hook_facebookactivity']}</h3>
	<div  class='block_list clearfix _sbcollapsable'>
		<div><fb:activity site=\"\" width=\"270\" height=\"300\" header=\"false\" border_color=\"#FFF\" colorscheme=\"light\" /></div>
	</div>
</div><div id=\"fb-root\"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '{$this->settings['fbc_appid']}', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/{$this->settings['fb_locale']}/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
") : ("")) . "";
return $IPBHTML;
}

/* -- hookGroupNameIndicator --*/
function hookGroupNameIndicator($groups=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookGroupNameIndicator'] ) )
{
$count_c428fe5ea7e7bfeef2e3dc971770d946 = is_array($this->functionData['hookGroupNameIndicator']) ? count($this->functionData['hookGroupNameIndicator']) : 0;
$this->functionData['hookGroupNameIndicator'][$count_c428fe5ea7e7bfeef2e3dc971770d946]['groups'] = $groups;
}
$IPBHTML .= "" . ((count( $groups )) ? ("
				<br />
				<ul>
					<li>" . implode( " | ", $groups ) . "</li>
				</ul>
") : ("")) . "";
return $IPBHTML;
}

/* -- hookRecentTopics --*/
function hookRecentTopics($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookRecentTopics'] ) )
{
$count_8e359c8b2f5cac11c7a26357bf5784f6 = is_array($this->functionData['hookRecentTopics']) ? count($this->functionData['hookRecentTopics']) : 0;
$this->functionData['hookRecentTopics'][$count_8e359c8b2f5cac11c7a26357bf5784f6]['topics'] = $topics;
}
$IPBHTML .= "" . ((is_array( $topics ) && count( $topics )) ? ("
<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['recently_added_topics']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_withminiphoto'>
		".$this->__f__70467c7affaecebbdc2f412cbbd491c2($topics)."		</ul>
	</div>
</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__70467c7affaecebbdc2f412cbbd491c2($topics)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li class='clearfix'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($r) : '' ) . "
			<div class='list_content'>
				<strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}", "public",'' ), "{$r['title_seo']}", "showtopic" ) . "\" rel='bookmark' class='ipsType_small' title='" . strip_tags($r['topic_title']) . " {$this->lang->words['topic_started_on']} " . $this->registry->getClass('class_localization')->getDate($r['start_date'],"LONG", 0) . "'>{$r['topic_title']}</a></strong>
				<p class='desc ipsType_smaller'>
					" . (($r['members_display_name']) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($r) : '' ) . "") : ("{$this->settings['guest_name_pre']}{$r['starter_name']}{$this->settings['guest_name_suf']}")) . "
					- " . $this->registry->getClass('class_localization')->getDate($r['start_date'],"short", 0) . "
				</p>
			</div>
		</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookTagCloud --*/
function hookTagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookTagCloud'] ) )
{
$count_f38f7f8d023ae9973c6a4e2f239a9630 = is_array($this->functionData['hookTagCloud']) ? count($this->functionData['hookTagCloud']) : 0;
$this->functionData['hookTagCloud'][$count_f38f7f8d023ae9973c6a4e2f239a9630]['tags'] = $tags;
}
$IPBHTML .= "<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['popular_tags']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_inline'>
		".$this->__f__24f20af600e79728166944118c65c103($tags)."		</ul>
	</div>
</div>";
return $IPBHTML;
}


function __f__24f20af600e79728166944118c65c103($tags)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tags['tags'] as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li><span class=\"{$data['className']}\">{$data['tagWithUrl']}</span></li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusReplies --*/
function statusReplies($replies=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['statusReplies'] ) )
{
$count_76aa6766723a4a3a8842a9b3a456f799 = is_array($this->functionData['statusReplies']) ? count($this->functionData['statusReplies']) : 0;
$this->functionData['statusReplies'][$count_76aa6766723a4a3a8842a9b3a456f799]['replies'] = $replies;
}
$IPBHTML .= "".$this->__f__5a47fa3493957a872b927dfe3dc6cafe($replies)."";
return $IPBHTML;
}


function __f__5a47fa3493957a872b927dfe3dc6cafe($replies=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $replies as $reply )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<div id='statusReply-{$reply['reply_id']}' class='ipsPad_half'>
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $reply, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$reply['members_display_name']) ) )) : '' ) . "
		<div class='list_content'>
			<div class='right lighter'>
				<span class='desc ipsType_smaller'>" . $this->registry->getClass('class_localization')->getDate($reply['reply_date'],"manual{%d %b}", 0) . "&nbsp;&nbsp;</span>
				<span class='desc mod_links ipsType_smaller'>
					" . (($reply['_canDelete']) ? ("<a href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteReply&amp;status_id={$reply['reply_status_id']}&amp;reply_id={$reply['reply_id']}&amp;k={$this->member->form_hash}\" id=\"statusReplyDelete-{$reply['reply_status_id']}-{$reply['reply_id']}\" class=\"__sDR __dr{$reply['reply_status_id']}-{$reply['reply_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
				</span>
			</div>
			<strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($reply) : '' ) . "</strong>
			<p class='index_status_update ipsType_small'>{$reply['reply_content']}</p>
		</div>
	</div>
	" . (($__iteratorCount == count($replies)) ? ("
		<div id='statusReplyBlank-{$reply['reply_status_id']}' style='display: none'></div>
	") : ("")) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusUpdates --*/
function statusUpdates($updates=array(), $smallSpace=0, $latestOnly=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['statusUpdates'] ) )
{
$count_45458227dd419ae189a866ffde8570ba = is_array($this->functionData['statusUpdates']) ? count($this->functionData['statusUpdates']) : 0;
$this->functionData['statusUpdates'][$count_45458227dd419ae189a866ffde8570ba]['updates'] = $updates;
$this->functionData['statusUpdates'][$count_45458227dd419ae189a866ffde8570ba]['smallSpace'] = $smallSpace;
$this->functionData['statusUpdates'][$count_45458227dd419ae189a866ffde8570ba]['latestOnly'] = $latestOnly;
}
$IPBHTML .= "<script type=\"text/javascript\">
	ipb.status.maxReplies = " . intval($this->settings['su_max_replies']) . ";
	ipb.status.smallSpace = " . intval($smallSpace) . ";
	ipb.status.skin_group = 'boards';
</script>".$this->__f__594912ecef48c9f1735f7b0c8d35ec38($updates,$smallSpace,$latestOnly)."";
return $IPBHTML;
}


function __f__594912ecef48c9f1735f7b0c8d35ec38($updates=array(), $smallSpace=0, $latestOnly=0)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $updates as $id => $status )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . (($this->memberData['member_id'] AND $latestOnly AND $status['member_id'] == $this->memberData['member_id']) ? ("
		<script type=\"text/javascript\">
			ipb.status.myLatest = {$status['status_id']};
		</script>
	") : ("")) . "
	<ul class='ipsList_withminiphoto status_list' id='statusWrap-{$status['status_id']}'>
		<li class='clearfix'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($status) : '' ) . "
			<div class='list_content'>
				<div id=\"statusContent-{$status['status_id']}\">
					<div class='right desc lighter'>
						<span class='desc mod_links ipsType_smaller'>
							" . (($status['_canDelete']) ? ("<a rel=\"nofollow\" href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusDelete-{$status['status_id']}\" class=\"__sD __d{$status['status_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
							<span id='statusUnlock-{$status['status_id']}' " . (($status['_isLocked'] AND $status['_canUnlock']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=unlockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusUnlockLink-{$status['status_id']}\" class=\"__sU __u{$status['status_id']}\">{$this->lang->words['status_unlock_link']}</a></span>
							<span id='statusLock-{$status['status_id']}' " . (($status['_canLock'] AND ! $status['_isLocked']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=lockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusLockLink-{$status['status_id']}\" class=\"__sL __l{$status['status_id']}\">{$this->lang->words['status_lock_link']}</a></span>
						</span>
						&nbsp;&nbsp;<span class='ipsType_smaller blend_links'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=single&amp;status_id={$status['status_id']}", "public",'' ), array($status['member_id'], $status['members_seo_name']), "members_status_single" ) . "'>" . $this->registry->getClass('class_localization')->getDate($status['status_date'],"manual{%d %b}", 0) . "</a></span>
					</div>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($status) : '' ) . "
					<p class='index_status_update ipsType_small'>{$status['status_content']}</p>
					<span class='desc' id='statusToggle-{$status['status_id']}'>
						<img src=\"{$this->settings['img_url']}/icon_lock.png\" id='statusLockImg-{$status['status_id']}' alt=\"{$this->lang->words['status__locked']}\" " . ((!$status['status_is_locked']) ? ("style='display: none'") : ("")) . " />
						" . ((! $smallSpace AND $status['_creatorImg']) ? ("<img src=\"{$status['_creatorImg']}\" alt='' data-tooltip=\"{$this->lang->words['su_via']} {$status['_creatorText']}\" />") : ("")) . "
						" . (($status['_userCanReply']) ? ("" . (($status['status_replies']) ? ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller \">" . sprintf( $this->lang->words['view_comments_and_add'], $status['status_replies']) . "</a>
							") : ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller\">{$this->lang->words['add_comments_only']}</a>
							")) . "") : ("" . (($status['status_replies']) ? ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller\">" . sprintf( $this->lang->words['view_comments_only'], $status['status_replies']) . "</a>
							") : ("")) . "")) . "
					</span>
					<span class='desc' id='statusToggleOff-{$status['status_id']}' style='display:none'>
						<a href=\"#\" class=\"__sTO __to{$status['status_id']}\">{$this->lang->words['view_comments_collapse']}</a>
					</span>
				</div>
			</div>
			<div id=\"statusFeedback-{$status['status_id']}\" class='status_feedback' style='display:none'>
				<div class='ipsList_withtinyphoto status_list' id='statusReplies-{$status['status_id']}'>
					" . (($status['status_replies'] AND count( $status['replies'] )) ? ("" . (($status['status_replies'] > 3) ? ("
							<div class='status_mini_wrap row2 altrow' id='statusMoreWrap-{$status['status_id']}'>
								<img src=\"{$this->settings['img_url']}/comments.png\" alt=\"\" /> &nbsp;<a href=\"#\" id=\"statusMore-{$status['status_id']}\" class='__showAll __x{$status['status_id']}'>" . sprintf( $this->lang->words['status_show_all_x'], $status['status_replies'] ) . "</a>
							</div>
						") : ("")) . "
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'statusReplies' ) ? $this->registry->getClass('output')->getTemplate('boards')->statusReplies($status['replies']) : '' ) . "") : ("
						<div id='statusReplyBlank-{$status['status_id']}' style='display: none'></div>
					")) . "
				</div>
				" . (($status['_userCanReply']) ? ("
					<div class='ipsList_withtinyphoto status_list status_reply clearfix ipsPad_half' id='statusReply-{$status['status_id']}'>
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $this->memberData, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$this->memberData['members_display_name']) ) )) : '' ) . "
						<div class='list_content'>
							<form id='statusReplyForm-{$status['status_id']}' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=reply&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}' method='post'>
								<textarea class='status_textarea' rows='3' cols='50' name='comment-{$status['status_id']}' id='statusText-{$status['status_id']}'></textarea>
								<div class=\"status_submit\"><input type='submit' class='__submit input_submit' id='statusSubmit-{$status['status_id']}' value='{$this->lang->words['status__dfcomment']}' /></div>
							</form>
							<a href='#' class='__showform' id='statusReplyFormShow-{$status['status_id']}' style='display: none'>{$this->lang->words['status__addcomment']}</a>
						</div>
					</div>
					<script type='text/javascript'>
						if( $('statusReplyForm-{$status['status_id']}') ){
							$('statusReplyForm-{$status['status_id']}').hide();
						}
						if( $('statusReplyFormShow-{$status['status_id']}') ){
							$('statusReplyFormShow-{$status['status_id']}').show();
						}
					</script>
				") : ("")) . "
			</div>
		</li>
	</ul>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- top_reputation_link --*/
function top_reputation_link($link) {
$IPBHTML = "";
$IPBHTML .= "{$link}";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>