<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 09 May 2013 09:22:44 +0000 by KulleR
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'cookie__acp_mergecenter' => "АЦ: ID стилей для слияния",
'cookie__acp_mergecenter__desc' => "Устанавливается, когда выбираются стили для слияния",
'cookie__acp_sidebar' => "АЦ: Статус боковой панели",
'cookie__acp_sidebar__desc' => "Установлено, когда боковая панель скрывается/отображается",
'cookie__anonlogin' => "Анонимный вход",
'cookie__anonlogin__desc' => "Устанавливается, если вы выбрали \"анонимный вход\" при вводе пароля",
'cookie__commentmodpids' => "ID выбранных комментариев (При модерации)",
'cookie__commentmodpids__desc' => "Устанавливается, когда выбираются комментарии для моддерации",
'cookie__coppa' => "Флаг регистрации Coppa",
'cookie__coppa__desc' => "Устанавливается, если при регистрации возраст пользователя был определен, как не достигший 13 лет",
'cookie__emoticon_sidebar' => "Статус панели смайликов в редакторе",
'cookie__emoticon_sidebar__desc' => "Устанавливается, когда переключается состояние панели смайликов",
'cookie__guestSkinChoice' => "Стиль Гостя",
'cookie__guestSkinChoice__desc' => "Устанавливается, если гость выбрал стиль для отображения. Для зарегистрированных пользователей эта настройка храниться в БД.",
'cookie__ignore-license-notice' => "АЦ: Запоминает статус сообщение о лицензии",
'cookie__ignore-license-notice__desc' => "Установливается, чтобы скрыть сообщение об отсутствии или истечении лицензии",
'cookie__language' => "Язык Гостя",
'cookie__language__desc' => "Содержит идентификатор языка, выбранный гостем. Для зарегистрированных пользователей эта настройка храниться в БД.",
'cookie__member_id' => "Идентификатор Пользователя",
'cookie__member_id__desc' => "Идентификатор авторизованного пользователя",
'cookie__mobileApp' => "Флаг Мобильного Приложения",
'cookie__mobileApp__desc' => "Устанавливается, если используется мобильное приложение",
'cookie__mobileBrowser' => "Флаг мобильного браузера",
'cookie__mobileBrowser__desc' => "Устанавливается, если вы используете мобильный браузер, напр. Safari на вашем iPhone",
'cookie__pass_hash' => "Ключ для входа",
'cookie__pass_hash__desc' => "Ключ для автоматического входа на форум.",
'cookie__rteStatus' => "Состояние Редактора",
'cookie__rteStatus__desc' => "Устанавливается, когда переключается режим редактора сообщений",
'cookie__session_id' => "Идентификатор Сессии",
'cookie__session_id__desc' => "MD5()-Ключ сессии пользователя",
'cookie__sfc' => "Врема последнего поискового запроса",
'cookie__sfct' => "Последний Поисковый Запрос",
'cookie__sfct__desc' => "Хранит содержимое последнего поискового запроса",
'cookie__sfc__desc' => "Содержит время вашего последнего поискового запроса в формате unix",
'cookie__uagent_bypass' => "Обойти Определение UserAgent",
'cookie__uagent_bypass__desc' => "Устанавливается, если вы нажимаете \"Полная версия\" в мобильном стиле внешнего вида",
 ); 
