<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 09 May 2013 09:22:44 +0000 by KulleR
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'fave_title' => "%s",
'freq_daily' => "Ежедневно",
'freq_immediate' => "Немедленно",
'freq_offline' => "Только, когда не в онлайне",
'freq_weekly' => "Еженедельно",
'label_anon' => "Следить анонимно",
'label_anon_desc' => "Не показывать меня в выборке",
'label_freq' => "Частота",
'label_notify' => "Получать уведомление",
'likeadded' => "Добавлено:",
'likedby' => "Следят",
'pg_no_longer_following' => "Вы больше не отслеживаете это",
'pg_unfollow_confirm' => "Прекратить отслеживание",
'pg_unfollow_text' => "<strong>%s</strong>, вы хотите прекратить отслеживание <a href='%s'>%s</a>.<br />При отключении отслеживания вы больше не будете получать уведомления об обновлениях.",
'pg_unfollow_title' => "Прекратить отслеживание",
'pg_unlike_done' => "Вы прекратили отслеживание",
 ); 
