<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 09 May 2013 09:22:44 +0000 by KulleR
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'cookie__has_sidebar' => "Отображение Боковой Панели на Главной Странице",
'cookie__has_sidebar__desc' => "Устанавливается при переключении статуса отображения боковой панели на главной странице форума",
'cookie__ipbforumpass_*' => "Пароль Форума",
'cookie__ipbforumpass_*__desc' => "Устанавливается, когда вы вводите пароль для защищенного форума",
'cookie__modpids' => "Идентификаторы Выбранных Сообщений(при модерации)",
'cookie__modpids__desc' => "Устанавливается, когда вы выбираете сообщения для модерации",
'cookie__modtids' => "Идентификаторы Выбранных Тем(при модерации)",
'cookie__modtids__desc' => "Устанавливается, когда вы выбираете темы для модерации",
'cookie__mqtids' => "Идентификаторы Выбранных Сообщений(при мультицитировании)",
'cookie__mqtids__desc' => "Устанавливается, когда вы выбираете сообщения для мульти-цитаты",
'cookie__toggleCats' => "Статус Категории",
'cookie__toggleCats__desc' => "Устанавливается, когда изменяется статус отображения категории",
 ); 
