<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 09 May 2013 09:22:44 +0000 by KulleR
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'back_topic' => "Вернуться в тему",
'by' => "Автор:",
'click_toview' => "Перейти в тему",
'end' => "конец",
'forum' => "Форум",
'on	' => " —  ",
'o_html_desc' => "Вы можете скачать HTML версию этой темы на ваш компьютер. Будет открыто окно для скачивания.",
'o_html_title' => "HTML версия",
'o_print_desc' => "Тема будет отображена и распечатана в простом виде на этой странице.",
'o_print_title' => "Версия для печати",
'o_word_desc' => "Вы можете скачать Word версию этой темы с возможностью дальнейшего редактирования. Будет открыто окно для скачивания.",
'o_word_title' => "Версия в формате Microsoft Word",
'please_choose' => "Пожалуйста, выберите нужный формат",
'posted_prefix' => "Отправлено",
'powered_by' => "Русский ",
'start' => "создал ",
'title' => "Версия темы для печати",
'topic' => "Тема",
'tvo_title' => "Опции отображения темы для:",
'view_original' => "(Нажмите сюда для просмотра этой темы в обычном формате)",
 ); 
