<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 09 May 2013 09:22:44 +0000 by KulleR
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'mem_change_button' => "Изменить",
'mem_posts' => "Сообщения",
'm_overrride' => "Переопределить права группы следующими масками",
 ); 
