<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Thu, 09 May 2013 09:22:44 +0000 by KulleR
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'publicArticleCommenting' => "Используется для возврата данных в формате JSON для системы комментариев.",
 ); 
