<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Wed, 08 May 2013 03:43:50 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_vkontakte_1 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['membersVkontakteConnect'] = array('vkHasPic','vkHasPic','vkPassword');


}

/* -- membersVkontakteConnect --*/
function membersVkontakteConnect($isConnected, $userData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_vkontakte', $this->_funcHooks['membersVkontakteConnect'] ) )
{
$count_c00010c0504aac839f5504f7d7b8c61f = is_array($this->functionData['membersVkontakteConnect']) ? count($this->functionData['membersVkontakteConnect']) : 0;
$this->functionData['membersVkontakteConnect'][$count_c00010c0504aac839f5504f7d7b8c61f]['isConnected'] = $isConnected;
$this->functionData['membersVkontakteConnect'][$count_c00010c0504aac839f5504f7d7b8c61f]['userData'] = $userData;
}

if ( ! isset( $this->registry->templateStriping['usercp'] ) ) {
$this->registry->templateStriping['usercp'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . ((!$isConnected) ? ("
<div>
	<p class='message'>{$this->lang->words['vk_config']}</p>
	<br />
	<br />
	<a href=\"{$this->settings['_original_base_url']}/interface/vkontakte/index.php\"><img src=\"{$this->settings['img_url']}/vkontakte_login.png\" alt=\"\" /></a>
	<br />
</div>
") : ("<div>
	<div class='ipsPad row2 clearfix'>
		" . (($userData['photo']) ? ("	
			<img src=\"{$userData['photo']}\" alt='' class='left ipsUserPhoto ipsUserPhoto_medium' />
			<div class='ipsBox_withphoto'>
		") : ("")) . "
		<h2 class='ipsType_subtitle'>
			{$this->lang->words['vk_logged_in_as']} <strong>{$userData['first_name']} {$userData['last_name']}</strong>
		</h2>
		" . (($userData['photo']) ? ("
			</div>
		") : ("")) . "
	</div>

	<br />
	<div class='right row2 ipsPad clearfix' style='width: 250px'>
		<input type='button' class='ipsButton_secondary' id='vk_remove_start' value='{$this->lang->words['vk_disassociate']}' />

		<div id='vk_remove_popup' style='display: none'>
			<h3>{$this->lang->words['vk_disassociate']}</h3>
			<div class='ipsPad'>
				<p>{$this->lang->words['vk_revoke']}</p>
				<p class='desc'>{$this->lang->words['vk_disassociate_desc']}</p>
				<br />
				<input type='button' class='ipsButton' id='vk_remove' value='{$this->lang->words['tc_disassociate_now']}' />
			</div>
		</div>
	</div>

	" . ((! $this->memberData['bw_local_password_set'] AND $this->memberData['members_created_remote']) ? ("
		<div class='message'>
			<strong>{$this->lang->words['remote_no_password']}</strong>
			<p>{$this->lang->words['remote_no_password_1']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=usercp&amp;tab=core&amp;area=password", "public",'' ), "", "" ) . "'>{$this->lang->words['remote_no_password_2']}</a>
			</p>
		</div>
		<br />
	") : ("")) . "
</div>
<script type=\"text/javascript\">
	$('vk_remove').observe( 'click', usercp_remove );
	function usercp_remove(){
		window.location = ipb.vars['base_url'] + 'app=core&module=usercp&tab=core&area=vkontakteRemove&do=custom&secure_key=' + ipb.vars['secure_hash'];
	}

	$('vk_remove_start').on('click', function(e){
		new ipb.Popup( 'sign_in_popup', {	type: 'pane',
											initial: $('vk_remove_popup').show(),
											hideAtStart: false,
											hideClose: false,
											modal: true,
											w: '600px' } );
	});
</script>")) . "";
return $IPBHTML;
}

/* -- vkInlineLogInService --*/
function vkInlineLogInService() {
$IPBHTML = "";
$IPBHTML .= "<li><a href=\"{$this->settings['_original_base_url']}/interface/vkontakte/index.php?_reg=1\"><img src=\"{$this->settings['img_url']}/vkontakte_login.png\" alt=\"\" /></a></li>";
return $IPBHTML;
}

/* -- vkServicesLim --*/
function vkServicesLim() {
$IPBHTML = "";
$IPBHTML .= "<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login&amp;serviceClick=vkontakte", "public",'' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("lim_vkontakte") . "</a>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>